// Central list of US ski resorts for /api/snow
// Keep this file pure data so it can be reused by scripts later.

export const RESORTS = [
  // California
  {
    name: "Palisades Tahoe",
    state: "CA",
    region: "Olympic Valley, CA",
    elevation_ft: 6200,
    lat: 39.1973,
    lon: -120.2358,
    report_url: "https://www.palisadestahoe.com/mountain-information/snow-and-weather-report",
    webcam_url: "https://www.palisadestahoe.com/mountain-information/webcams",
  },
  {
    name: "Heavenly",
    state: "CA",
    region: "South Lake Tahoe, CA",
    elevation_ft: 10067,
    lat: 38.9351,
    lon: -119.939,
    report_url: "https://www.skiheavenly.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx",
    webcam_url: "https://www.skiheavenly.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  },
  {
    name: "Northstar California",
    state: "CA",
    region: "Truckee, CA",
    elevation_ft: 8610,
    lat: 39.2746,
    lon: -120.121,
    report_url: "https://www.northstarcalifornia.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx",
    webcam_url: "https://www.northstarcalifornia.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  },
  {
    name: "Kirkwood",
    state: "CA",
    region: "Kirkwood, CA",
    elevation_ft: 9800,
    lat: 38.6846,
    lon: -120.065,
    report_url: "https://www.kirkwood.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx",
    webcam_url: "https://www.kirkwood.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  },
  {
    name: "Mammoth Mountain",
    state: "CA",
    region: "Mammoth Lakes, CA",
    elevation_ft: 11053,
    lat: 37.6308,
    lon: -119.0326,
    report_url: "https://www.mammothmountain.com/on-the-mountain/mountain-information/snow-report",
    webcam_url: "https://www.mammothmountain.com/on-the-mountain/mountain-information/webcams",
  },
  {
    name: "Big Bear Mountain Resort",
    state: "CA",
    region: "Big Bear Lake, CA",
    elevation_ft: 8805,
    lat: 34.2369,
    lon: -116.889,
    report_url: "https://www.bigbearmountainresort.com/mountain-information/snow-report",
    webcam_url: "https://www.bigbearmountainresort.com/mountain-information/webcams",
  },

  // Oregon
  {
    name: "Mt. Bachelor",
    state: "OR",
    region: "Bend, OR",
    elevation_ft: 9065,
    lat: 43.9793,
    lon: -121.6881,
    report_url: "https://www.mtbachelor.com/the-mountain/mountain-report",
    webcam_url: "https://www.mtbachelor.com/the-mountain/webcams",
  },

  // Washington
  {
    name: "Crystal Mountain",
    state: "WA",
    region: "Enumclaw, WA",
    elevation_ft: 7012,
    lat: 46.9364,
    lon: -121.4749,
    report_url: "https://www.crystalmountainresort.com/the-mountain/mountain-report",
    webcam_url: "https://www.crystalmountainresort.com/the-mountain/webcams",
  },
  {
    name: "Stevens Pass",
    state: "WA",
    region: "Skykomish, WA",
    elevation_ft: 5845,
    lat: 47.745,
    lon: -121.089,
    report_url: "https://www.stevenspass.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx",
    webcam_url: "https://www.stevenspass.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  },

  // Idaho
  {
    name: "Sun Valley",
    state: "ID",
    region: "Sun Valley, ID",
    elevation_ft: 9150,
    lat: 43.697,
    lon: -114.351,
    report_url: "https://www.sunvalley.com/mountain/snow-report/",
    webcam_url: "https://www.sunvalley.com/mountain/webcams/",
  },
  {
    name: "Schweitzer",
    state: "ID",
    region: "Sandpoint, ID",
    elevation_ft: 6400,
    lat: 48.368,
    lon: -116.623,
    report_url: "https://www.schweitzer.com/mountain-report/",
    webcam_url: "https://www.schweitzer.com/webcams/",
  },

  // Montana
  {
    name: "Big Sky",
    state: "MT",
    region: "Big Sky, MT",
    elevation_ft: 11166,
    lat: 45.284,
    lon: -111.401,
    report_url: "https://bigskyresort.com/snow-report",
    webcam_url: "https://bigskyresort.com/webcams",
  },

  // Utah
  {
    name: "Park City",
    state: "UT",
    region: "Park City, UT",
    elevation_ft: 10026,
    lat: 40.6514,
    lon: -111.507,
    report_url: "https://www.parkcitymountain.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx",
    webcam_url: "https://www.parkcitymountain.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  },
  {
    name: "Deer Valley",
    state: "UT",
    region: "Park City, UT",
    elevation_ft: 9570,
    lat: 40.6374,
    lon: -111.4783,
    report_url: "https://www.deervalley.com/explore-the-mountain/mountain-report",
    webcam_url: "https://www.deervalley.com/explore-the-mountain/webcams",
  },
  {
    name: "Snowbird",
    state: "UT",
    region: "Snowbird, UT",
    elevation_ft: 11000,
    lat: 40.5803,
    lon: -111.6547,
    report_url: "https://www.snowbird.com/mountain-report/",
    webcam_url: "https://www.snowbird.com/webcams/",
  },
  {
    name: "Alta",
    state: "UT",
    region: "Alta, UT",
    elevation_ft: 11068,
    lat: 40.5883,
    lon: -111.637,
    report_url: "https://www.alta.com/weather",
    webcam_url: "https://www.alta.com/webcams",
  },

  // Colorado
  {
    name: "Vail",
    state: "CO",
    region: "Vail, CO",
    elevation_ft: 11570,
    lat: 39.6403,
    lon: -106.3742,
    report_url: "https://www.vail.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx",
    webcam_url: "https://www.vail.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  },
  {
    name: "Beaver Creek",
    state: "CO",
    region: "Beaver Creek, CO",
    elevation_ft: 11440,
    lat: 39.6042,
    lon: -106.5165,
    report_url: "https://www.beavercreek.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx",
    webcam_url: "https://www.beavercreek.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  },
  {
    name: "Breckenridge",
    state: "CO",
    region: "Breckenridge, CO",
    elevation_ft: 12998,
    lat: 39.4817,
    lon: -106.0384,
    report_url: "https://www.breckenridge.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx",
    webcam_url: "https://www.breckenridge.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  },
  {
    name: "Keystone",
    state: "CO",
    region: "Keystone, CO",
    elevation_ft: 12408,
    lat: 39.5792,
    lon: -105.9347,
    report_url: "https://www.keystoneresort.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx",
    webcam_url: "https://www.keystoneresort.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  },
  {
    name: "Arapahoe Basin",
    state: "CO",
    region: "Dillon, CO",
    elevation_ft: 13050,
    lat: 39.6423,
    lon: -105.8717,
    report_url: "https://www.arapahoebasin.com/snow-report/",
    webcam_url: "https://www.arapahoebasin.com/webcams/",
  },
  {
    name: "Copper Mountain",
    state: "CO",
    region: "Copper Mountain, CO",
    elevation_ft: 12313,
    lat: 39.5022,
    lon: -106.1511,
    report_url: "https://www.coppercolorado.com/the-mountain/mountain-information/snow-report",
    webcam_url: "https://www.coppercolorado.com/the-mountain/mountain-information/webcams",
  },
  {
    name: "Loveland",
    state: "CO",
    region: "Georgetown, CO",
    elevation_ft: 13010,
    lat: 39.68,
    lon: -105.897,
    report_url: "https://skiloveland.com/snow-report/",
    webcam_url: "https://skiloveland.com/webcams/",
  },
  {
    name: "Winter Park",
    state: "CO",
    region: "Winter Park, CO",
    elevation_ft: 12060,
    lat: 39.8868,
    lon: -105.7625,
    report_url: "https://www.winterparkresort.com/the-mountain/mountain-report",
    webcam_url: "https://www.winterparkresort.com/the-mountain/mountain-cams",
  },
  {
    name: "Steamboat",
    state: "CO",
    region: "Steamboat Springs, CO",
    elevation_ft: 10568,
    lat: 40.4572,
    lon: -106.804,
    report_url: "https://www.steamboat.com/the-mountain/mountain-report",
    webcam_url: "https://www.steamboat.com/the-mountain/mountain-cams",
  },
  {
    name: "Aspen Snowmass",
    state: "CO",
    region: "Snowmass Village, CO",
    elevation_ft: 12510,
    lat: 39.2097,
    lon: -106.949,
    report_url: "https://www.aspensnowmass.com/mountain/snow-report",
    webcam_url: "https://www.aspensnowmass.com/mountain/webcams",
  },
  {
    name: "Crested Butte",
    state: "CO",
    region: "Crested Butte, CO",
    elevation_ft: 12162,
    lat: 38.8994,
    lon: -106.9659,
    report_url: "https://www.skicb.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx",
    webcam_url: "https://www.skicb.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  },
  {
    name: "Telluride",
    state: "CO",
    region: "Telluride, CO",
    elevation_ft: 13150,
    lat: 37.9363,
    lon: -107.8466,
    report_url: "https://tellurideskiresort.com/mountain/snow-report/",
    webcam_url: "https://tellurideskiresort.com/mountain/webcams/",
  },

  // Wyoming
  {
    name: "Jackson Hole",
    state: "WY",
    region: "Teton Village, WY",
    elevation_ft: 10450,
    lat: 43.5875,
    lon: -110.8278,
    report_url: "https://www.jacksonhole.com/mountain-report",
    webcam_url: "https://www.jacksonhole.com/webcams",
  },

  // New Mexico
  {
    name: "Taos Ski Valley",
    state: "NM",
    region: "Taos Ski Valley, NM",
    elevation_ft: 12481,
    lat: 36.596,
    lon: -105.454,
    report_url: "https://www.skitaos.com/mountain-report",
    webcam_url: "https://www.skitaos.com/webcams",
  },

  // Arizona
  {
    name: "Arizona Snowbowl",
    state: "AZ",
    region: "Flagstaff, AZ",
    elevation_ft: 11500,
    lat: 35.3319,
    lon: -111.708,
    report_url: "https://www.snowbowl.ski/mountain-report/",
    webcam_url: "https://www.snowbowl.ski/webcams/",
  },

  // Nevada
  {
    name: "Mt. Rose",
    state: "NV",
    region: "Reno, NV",
    elevation_ft: 9700,
    lat: 39.313,
    lon: -119.885,
    report_url: "https://skirose.com/snow-report/",
    webcam_url: "https://skirose.com/webcams/",
  },

  // New York
  {
    name: "Whiteface",
    state: "NY",
    region: "Wilmington, NY",
    elevation_ft: 4867,
    lat: 44.365,
    lon: -73.903,
    report_url: "https://whiteface.com/mountain/conditions/",
    webcam_url: "https://whiteface.com/mountain/conditions/",
  },

  // Vermont
  {
    name: "Stowe",
    state: "VT",
    region: "Stowe, VT",
    elevation_ft: 4395,
    lat: 44.465,
    lon: -72.687,
    report_url: "https://www.stowe.com/the-mountain/mountain-conditions/snow-and-weather-report.aspx",
    webcam_url: "https://www.stowe.com/the-mountain/mountain-conditions/mountain-cams.aspx",
  },
  {
    name: "Killington",
    state: "VT",
    region: "Killington, VT",
    elevation_ft: 4241,
    lat: 43.626,
    lon: -72.796,
    report_url: "https://www.killington.com/the-mountain/conditions-weather/current-conditions-weather",
    webcam_url: "https://www.killington.com/the-mountain/conditions-weather/webcams",
  },

  // New Hampshire
  {
    name: "Bretton Woods",
    state: "NH",
    region: "Bretton Woods, NH",
    elevation_ft: 3100,
    lat: 44.258,
    lon: -71.441,
    report_url: "https://www.brettonwoods.com/mountain/snow-report",
    webcam_url: "https://www.brettonwoods.com/mountain/webcams",
  },

  // Maine
  {
    name: "Sugarloaf",
    state: "ME",
    region: "Carrabassett Valley, ME",
    elevation_ft: 4237,
    lat: 45.031,
    lon: -70.313,
    report_url: "https://www.sugarloaf.com/mountain-report",
    webcam_url: "https://www.sugarloaf.com/mountain-report",
  },
];
